In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv("./gold.csv")
data[:6]

Date    Rates
0  30 Sep 2020  1892.62
1  29 Sep 2020  1896.80
2  28 Sep 2020  1882.46
3  25 Sep 2020  1861.33
4  24 Sep 2020  1867.99
5  23 Sep 2020  1855.03

In [2]:
rates = data['Rates']
sum(rates.isnull())

24

In [3]:
rates = rates.fillna(method="pad")

In [4]:
sum(rates.isnull())

0

In [5]:
# n = 5
# list_df = [rates[i:i+n] for i in range(0,rates.shape[0],n)]

In [8]:
rates.shape[0]

13361

In [142]:
p=5
pr = []
for i in range(0,rates.shape[0]):
    pr.append(rates[i+p])              #if it gave an error so ignore it and run further cells

In [10]:
pr[0],pr[1],pr[2]

(1855.03, 1904.4, 1917.23)

In [115]:
p=5
val= []
for i in range(0,rates.shape[0]):
    val.append(list(rates[i:i+p]))

In [116]:
np.array(val[0])

array([1892.62, 1896.8 , 1882.46, 1861.33, 1867.99])

In [117]:
len(pr),len(val)

(13356, 13361)

In [118]:
val = val[:len(pr)]    

In [119]:
len(pr),len(val)

(13356, 13356)

In [120]:
val[0]

[1892.62, 1896.8, 1882.46, 1861.33, 1867.99]

In [121]:
# data_csv = []
# for i in range(len(rates)):
#     data_csv.append([data["Date"].iloc[i],rates.iloc[i]])

In [122]:
# len(data_csv),data_csv[0]

In [123]:
# data_csv = np.array(data_csv)
# length = len(data_csv)
# print(length,data_csv.shape)

# data_csv = np.insert(data_csv, 0, ["Dates","Rates"])
# data_csv = data_csv.reshape( (length+1, 2) )
# len(data_csv)

In [124]:
# data_csv

In [125]:
# import csv
# with open('new_gold.csv', 'w', newline='') as file:
#     writer = csv.writer(file)
#     writer.writerows(data_csv)

In [126]:
val[0]

[1892.62, 1896.8, 1882.46, 1861.33, 1867.99]

In [128]:
dataset = []
for i in range(len(pr)):
    row = list(val[i])
    row.append(pr[i])
    dataset.append(row)

In [129]:
len(dataset), np.array(dataset).shape,type(dataset)

(13356, (13356, 6), list)

In [130]:
dataset[0],val[0],pr[0]

([1892.62, 1896.8, 1882.46, 1861.33, 1867.99, 1855.03],
 [1892.62, 1896.8, 1882.46, 1861.33, 1867.99],
 1855.03)

In [131]:
dataset = np.array(dataset)
np.random.shuffle(dataset)
np.random.shuffle(dataset)
dataset.shape

(13356, 6)

In [132]:
dataset2 = list(dataset)                           # dataset2 = dataset
append_item = dataset[0]                           # length = len(dataset2)
                                                   # # shape = dataset2[0].shape
dataset2[0] = ["v1","v2","v3","v4","v5","target"]  # print(length,type(dataset2))

dataset2.append(append_item)
len(dataset2),len(dataset)                      # header = ["value1","value2","value3","value4","value5","target"]
                                                # dataset2 = np.insert(dataset2,0,header)
                                                # # dataset2 = dataset2.reshape( (length+1, 6 ) )
                                                # # len(dataset2),dataset2.shape

(13357, 13356)

In [133]:
np.array(dataset2).shape, dataset2[:10]

((13357, 6),
 [['v1', 'v2', 'v3', 'v4', 'v5', 'target'],
  array([48.38, 48.4 , 48.38, 48.41, 48.46, 48.4 ]),
  array([173.  , 174.5 , 174.  , 172.25, 176.75, 177.5 ]),
  array([273.75, 272.3 , 272.55, 272.7 , 273.35, 272.55]),
  array([453.95, 454.9 , 452.4 , 450.9 , 450.6 , 453.75]),
  array([1232.7 , 1221.02, 1225.9 , 1219.  , 1231.19, 1237.2 ]),
  array([390.39, 397.35, 400.13, 400.4 , 398.66, 399.33]),
  array([225.5 , 223.15, 218.6 , 226.8 , 220.65, 220.5 ]),
  array([694.3 , 681.6 , 681.  , 671.8 , 673.05, 665.65]),
  array([152.8 , 150.4 , 152.  , 150.05, 148.9 , 147.5 ])])

In [136]:
import csv
with open('Gold Rates Dataset.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(dataset2)

In [137]:
df = pd.read_csv("Gold Rates Dataset.csv")

In [140]:
df.head()

v1       v2       v3       v4       v5   target
0    48.38    48.40    48.38    48.41    48.46    48.40
1   173.00   174.50   174.00   172.25   176.75   177.50
2   273.75   272.30   272.55   272.70   273.35   272.55
3   453.95   454.90   452.40   450.90   450.60   453.75
4  1232.70  1221.02  1225.90  1219.00  1231.19  1237.20

In [189]:
from fetch_data import get_latest_data

In [194]:
latest_data = get_latest_data() 
latest_data 
#will fetch 5 latest data

Fetching data......

01-Oct-2020 : 1897.79
30-Sep-2020 : 1887.78
29-Sep-2020 : 1896.8
28-Sep-2020 : 1882.46
25-Sep-2020 : 1861.33


['1897.79', '1887.78', '1896.80', '1882.46', '1861.33']

In [192]:
latest_data_with_range = get_latest_data(num=10)
#will fetch 10 latest data