In [11]:
from tensorflow.keras.models import load_model
from fetch_data import get_latest_data
import numpy
import json
import pprint

In [2]:
model = load_model("Gold_Price_Prediction_Model2.h5")

In [3]:
data = get_latest_data()

Fetching data......

13-Oct-2020 : 1919.7
12-Oct-2020 : 1924.9
09-Oct-2020 : 1930.33
08-Oct-2020 : 1895.3
07-Oct-2020 : 1887.07




In [4]:
len(data),data

(5, [1919.7, 1924.9, 1930.33, 1895.3, 1887.07])

In [8]:
li = []
for i in data:
    li.append(float(i)/100)
li = numpy.array(li)
li

array([19.197 , 19.249 , 19.3033, 18.953 , 18.8707])

In [24]:
def predict_1d(data):
    
    inp = numpy.array(data).reshape((1,5))  
    prediction = model.predict(inp)
    print("Predicted: %s"%(prediction[0][0]*100))
    return float(prediction[0][0]*100)

In [12]:
json_file = open("mean_info.json","r")
file = json.load(json_file)
pprint.pprint(file)

{'mean': [5.560248376786387,
          5.558829971031259,
          5.557766830822697,
          5.556212640981021,
          5.554484666859771],
 'std': [4.636739164735186,
         4.635057018774363,
         4.63457134642495,
         4.632804540472007,
         4.631256802795307]}


In [18]:
mean = numpy.array(file['mean'])
std = numpy.array(file['std'])
json_file.close()

In [20]:
mean,std

(array([5.56024838, 5.55882997, 5.55776683, 5.55621264, 5.55448467]),
 array([4.63673916, 4.63505702, 4.63457135, 4.63280454, 4.6312568 ]))

In [21]:
li -= mean
li /= std

In [22]:
li

array([2.94102194, 2.95361416, 2.96586936, 2.89172298, 2.87529193])

In [25]:
predicted_data = predict_1d(li)

Predicted: 1782.784652709961


In [47]:
import predict_for_tomorrow

In [49]:
predict_for_tomorrow.predict_for_tomorrow()

Fetching data......

13-Oct-2020 : 1919.7
12-Oct-2020 : 1924.9
09-Oct-2020 : 1930.33
08-Oct-2020 : 1895.3
07-Oct-2020 : 1887.07


Predicted: 1782.784652709961


1782.784652709961