### Download Following Dataset and use five text(use randomly generated 5 numbers and extract the data of the generated numbers from the dataset) to test the assignments.

In [1]:
text1 = "Unique Weird Orientalia from the 1930's: Exotic tales of the Orient from the 1930's. 'Dr Shen Fu', a Weird Tales magazine reprint, is about the elixir of life that grants immortality at a price. If you're tired of modern authors who all sound alike, this is the antidote for you. Owen's palette is loaded with splashes of Chinese and Japanese colours. Marvelous."

In [2]:
text2 = "Wonderful, baffling mix: This has just about everything. The rabbi, of course, is learned and devout, even if his schooling causes some nervousness. The cat becomes fantastical when some mystery grants him human speech. The visit abroad captures all the distrust of the alien that the most insular of small-towners can summon. And, around all of that, the monotonous drama of life unfolds: loves, losses, and changes that no one knows how to ride out.Comics have moved well past the BamPow genre into many other idioms - this might border on chick lit, but much less than some. If reality and fantasy remain negotiable for you, with deep family devotions and deeper (or shallower) personal ones, the ragged lines of this comic might touch you.-- wiredweird"

In [3]:
text3 = "No, not really: The title of this CD is misleading in an amazing number of ways. None of the songs are in any way related to rock music, nor, with one exception, are any of the artists. Even calling it a compilation of 60's folk music is a stretch. There are a handful of selections by artists from the early 60's folk scene, but planted among them are songs by a couple of 'folk-lite' bands (in the Kingston Trio/PP&M vein), two pop groups, and for some reason, a song by Traffic. I would be fascinated to learn what, in someone's mind, tied these together. Unless you are looking for a specific song, you can skip this one. Amazon sells dozens of other fine collections which better define both ""60's folk" "and ""the roots of rock"

In [4]:
text4 = "Colin Farrells performance is the only interesting thing here: Weak script, the actors do an acceptable job of trying to breathe some life and depth into it but they still dont manage to salvage the film. Theres an air of disdain and snottiness in the script-writers approach to the characters that makes them feel unemotional, plastic. Colin Farrell's role is brief and he plays the worst person in the film but he manages to inject the role with humanity. You believe he is a messed up sociopath but at the same time feel sorry for him on some level without this emotion being forced out of you.Which is good but stands in contrast to most of the rest of the film where the emotions feel forced,over the top and unbelievable. In short theres very few parts of the film where you believe this is anything but people reading lines and playing parts.Colin Farrell saved the film from the scrapheap but beyond his small part theres not much to recommend here unfortunately."

In [5]:
text5 = "Plays with it all the time!: I got this for my son when he was about a year old. He hasn't put it down since. The first thing he does is get out his clubs in the morning and now at 17 months he takes the cart every where. This is very durable and keeps him happy. I highly recommend."

In [6]:
samples = [text1,text2,text3,text4,text5]
samples

["Unique Weird Orientalia from the 1930's: Exotic tales of the Orient from the 1930's. 'Dr Shen Fu', a Weird Tales magazine reprint, is about the elixir of life that grants immortality at a price. If you're tired of modern authors who all sound alike, this is the antidote for you. Owen's palette is loaded with splashes of Chinese and Japanese colours. Marvelous.",
 'Wonderful, baffling mix: This has just about everything. The rabbi, of course, is learned and devout, even if his schooling causes some nervousness. The cat becomes fantastical when some mystery grants him human speech. The visit abroad captures all the distrust of the alien that the most insular of small-towners can summon. And, around all of that, the monotonous drama of life unfolds: loves, losses, and changes that no one knows how to ride out.Comics have moved well past the BamPow genre into many other idioms - this might border on chick lit, but much less than some. If reality and fantasy remain negotiable for you, wit

## 1)  One-hot coding of the following data using book codes (naive codes) of listing 6.1.

In [7]:
import numpy as np

### Tokenizing:

In [8]:
token_index = {}
for sample in samples:
    for word in sample.split():
        if word not in token_index:
            token_index[word] = len(token_index) + 1
print(token_index)

{'Unique': 1, 'Weird': 2, 'Orientalia': 3, 'from': 4, 'the': 5, "1930's:": 6, 'Exotic': 7, 'tales': 8, 'of': 9, 'Orient': 10, "1930's.": 11, "'Dr": 12, 'Shen': 13, "Fu',": 14, 'a': 15, 'Tales': 16, 'magazine': 17, 'reprint,': 18, 'is': 19, 'about': 20, 'elixir': 21, 'life': 22, 'that': 23, 'grants': 24, 'immortality': 25, 'at': 26, 'price.': 27, 'If': 28, "you're": 29, 'tired': 30, 'modern': 31, 'authors': 32, 'who': 33, 'all': 34, 'sound': 35, 'alike,': 36, 'this': 37, 'antidote': 38, 'for': 39, 'you.': 40, "Owen's": 41, 'palette': 42, 'loaded': 43, 'with': 44, 'splashes': 45, 'Chinese': 46, 'and': 47, 'Japanese': 48, 'colours.': 49, 'Marvelous.': 50, 'Wonderful,': 51, 'baffling': 52, 'mix:': 53, 'This': 54, 'has': 55, 'just': 56, 'everything.': 57, 'The': 58, 'rabbi,': 59, 'course,': 60, 'learned': 61, 'devout,': 62, 'even': 63, 'if': 64, 'his': 65, 'schooling': 66, 'causes': 67, 'some': 68, 'nervousness.': 69, 'cat': 70, 'becomes': 71, 'fantastical': 72, 'when': 73, 'mystery': 74, '

In [9]:
max_length = 50

### Null Matrix

In [10]:
results = np.zeros(shape=(len(samples),max_length,max(token_index.values()) + 1))
shape_of_1st_result = results.shape
print(shape_of_1st_result)
print("It means 5 sentences, \ntake maximum 50 words from each sentence, \nAnd each word can be of anyone from above dictionary")

(5, 50, 344)
It means 5 sentences, 
take maximum 50 words from each sentence, 
And each word can be of anyone from above dictionary


### One Hot Encoding

In [11]:
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = token_index.get(word)
        results[i, j, index] = 1

### Defining function to extract Word Encoding

In [12]:
def find_word(one_hot_encoded_list, sentence, word):
    print("One Hot Encoded word:",one_hot_encoded_list[sentence][word])

In [13]:
find_word(results,4,25)

One Hot Encoded word: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

## 2) Also, provide one-hot coding using Keras built-in function (listing 6.3).

### Importing Tokenizer from Keras

In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer

### Tokenizing

In [15]:
tokenizer = Tokenizer(num_words=1000)
tokenizer.fit_on_texts(samples)

# Words Dictionary

In [16]:
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

Found 315 unique tokens.


In [17]:
import itertools
for i in range(len(word_index)):
    dictionary = dict(itertools.islice(word_index.items(), i))
print("Dictionary after tokenizing:", dictionary)

Dictionary after tokenizing: {'the': 1, 'of': 2, 'and': 3, 'is': 4, 'a': 5, 'this': 6, 'to': 7, 'in': 8, 'you': 9, 'but': 10, 'he': 11, 'for': 12, 'some': 13, 'that': 14, 'with': 15, 'are': 16, 'film': 17, 'from': 18, 'all': 19, 'it': 20, 'about': 21, 'life': 22, 'at': 23, 'if': 24, 'his': 25, 'him': 26, 'one': 27, 'out': 28, 'an': 29, "60's": 30, 'by': 31, 'i': 32, 'colin': 33, 'theres': 34, 'feel': 35, 'where': 36, 'weird': 37, "1930's": 38, 'tales': 39, 'grants': 40, 'even': 41, 'when': 42, 'most': 43, 'small': 44, 'can': 45, 'no': 46, 'into': 47, 'other': 48, 'might': 49, 'on': 50, 'much': 51, 'lines': 52, 'not': 53, 'songs': 54, 'any': 55, 'rock': 56, 'music': 57, 'artists': 58, 'folk': 59, 'them': 60, 'song': 61, 'which': 62, 'thing': 63, 'here': 64, 'script': 65, 'role': 66, 'plays': 67, 'believe': 68, 'time': 69, 'forced': 70, 'very': 71, 'parts': 72, 'recommend': 73, 'unique': 74, 'orientalia': 75, 'exotic': 76, 'orient': 77, "'dr": 78, 'shen': 79, "fu'": 80, 'magazine': 81, '

### Sequence of Sentence after Tokenizing 

In [18]:
sequences = tokenizer.texts_to_sequences(samples)
print("Sequence of 1st Review:",sequences[0] )

Sequence of 1st Review: [74, 37, 75, 18, 1, 38, 76, 39, 2, 1, 77, 18, 1, 38, 78, 79, 80, 5, 37, 39, 81, 82, 4, 21, 1, 83, 2, 22, 14, 40, 84, 23, 5, 85, 24, 86, 87, 2, 88, 89, 90, 19, 91, 92, 6, 4, 1, 93, 12, 9, 94, 95, 4, 96, 15, 97, 2, 98, 3, 99, 100, 101]


### One Hot Encoding

In [19]:
one_hot_results = tokenizer.texts_to_matrix(samples, mode='binary')
shape_of_2nd_result = one_hot_results.shape
print(shape_of_2nd_result)
print("It means 5 sentences, \nEach Sentence has maximum 1000 words from above tokens\n")
print(one_hot_results)

(5, 1000)
It means 5 sentences, 
Each Sentence has maximum 1000 words from above tokens

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


### Defining function to extract Sentence Encoding

In [20]:
def find_sen(one_hot_encoded_list, sentence):
    print("One Hot Encoded sentence:",one_hot_encoded_list[sentence])

In [21]:
find_sen(one_hot_results,0)

One Hot Encoded sentence: [0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 

## 3) provide one-hot coding with hashing (listing 6.4)

### One-hot Encoding with Hashing trick 

In [22]:
import numpy as np

In [23]:
dimensionality = 1000
max_length = 10

### Null Marix

In [24]:
results = np.zeros((len(samples), max_length, dimensionality))
shape_of_3rd_result = results.shape
print(shape_of_3rd_result)
print("It means 5 sentences, \ntake maximum 10 words from each sentence, \nAnd each word can be of anyone from above 1000 words dictionary")

(5, 10, 1000)
It means 5 sentences, 
take maximum 10 words from each sentence, 
And each word can be of anyone from above 1000 words dictionary


### One Hot Encoding

In [25]:
key,value=[],[]
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        key.append(j)
        value.append(word)
        index = abs(hash(word)) % dimensionality
        results[i, j, index] = 1

### Values In Hashing Tecnique

In [26]:
for l in range(len(value)):
    print(f"{key[l]}:{value[l]}",end=', ')

0:Unique, 1:Weird, 2:Orientalia, 3:from, 4:the, 5:1930's:, 6:Exotic, 7:tales, 8:of, 9:the, 0:Wonderful,, 1:baffling, 2:mix:, 3:This, 4:has, 5:just, 6:about, 7:everything., 8:The, 9:rabbi,, 0:No,, 1:not, 2:really:, 3:The, 4:title, 5:of, 6:this, 7:CD, 8:is, 9:misleading, 0:Colin, 1:Farrells, 2:performance, 3:is, 4:the, 5:only, 6:interesting, 7:thing, 8:here:, 9:Weak, 0:Plays, 1:with, 2:it, 3:all, 4:the, 5:time!:, 6:I, 7:got, 8:this, 9:for, 

### Defining function to extract Word Encoding

In [27]:
def find_word(one_hot_encoded_list, sentence, word):
    print("One Hot Encoded word:",one_hot_encoded_list[sentence][word])

In [28]:
find_word(results,4,9)

One Hot Encoded word: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

## 4) Validate the how much they are similar. Try to maximize the similarity (ideally should be 100% the same). Specify the reason if both are not the same.

### Combining Shape of 1st, 2nd and 3rd Results

In [29]:
print("Normal Technique:",shape_of_1st_result)
print("In this Technique the sentence is limited to 50 words and each word can be of any unique "
      "word from the given data.\n")
print("Keras Tokenizer:",shape_of_2nd_result)
print("In this techinque, Each sentence is limited to 1000 words and keras encoded whole sentence"
      " at a time and saved the data in 1 list.\n")
print("Hashing Technique:",shape_of_3rd_result)
print("In this technique, Each sentence is limited to 10 words and each word can be of any "
     "one word from 1000 unique words.")

Normal Technique: (5, 50, 344)
In this Technique the sentence is limited to 50 words and each word can be of any unique word from the given data.

Keras Tokenizer: (5, 1000)
In this techinque, Each sentence is limited to 1000 words and keras encoded whole sentence at a time and saved the data in 1 list.

Hashing Technique: (5, 10, 1000)
In this technique, Each sentence is limited to 10 words and each word can be of any one word from 1000 unique words.


### Combining Tokenized Values

In [30]:
import itertools
for i in range(10):
    dict_1 = dict(itertools.islice(token_index.items(), i))
    dict_2 = dict(itertools.islice(word_index.items(), i))
print("1)In this Technique each word is uniquely tochnized.\n")
print(" Normal Technique:",dict_1,'\n')
print("2) In this Technique most commonly word was tokenized first.\n")
print(" Keras Tokenizer:",dict_2,'\n')
print("3) In this Technique each word is uniquely tochnized but it tokenized according "
     "to each sentence, not all combined.\n")
print(" Hashing Technique: ")
for l in range(len(value)):
    print(f"{key[l]}:{value[l]}",end=', ')

1)In this Technique each word is uniquely tochnized.

 Normal Technique: {'Unique': 1, 'Weird': 2, 'Orientalia': 3, 'from': 4, 'the': 5, "1930's:": 6, 'Exotic': 7, 'tales': 8, 'of': 9} 

2) In this Technique most commonly word was tokenized first.

 Keras Tokenizer: {'the': 1, 'of': 2, 'and': 3, 'is': 4, 'a': 5, 'this': 6, 'to': 7, 'in': 8, 'you': 9} 

3) In this Technique each word is uniquely tochnized but it tokenized according to each sentence, not all combined.

 Hashing Technique: 
0:Unique, 1:Weird, 2:Orientalia, 3:from, 4:the, 5:1930's:, 6:Exotic, 7:tales, 8:of, 9:the, 0:Wonderful,, 1:baffling, 2:mix:, 3:This, 4:has, 5:just, 6:about, 7:everything., 8:The, 9:rabbi,, 0:No,, 1:not, 2:really:, 3:The, 4:title, 5:of, 6:this, 7:CD, 8:is, 9:misleading, 0:Colin, 1:Farrells, 2:performance, 3:is, 4:the, 5:only, 6:interesting, 7:thing, 8:here:, 9:Weak, 0:Plays, 1:with, 2:it, 3:all, 4:the, 5:time!:, 6:I, 7:got, 8:this, 9:for, 

# SO, According to above Discussion Every Technique is different from each other and also has different results. 
# And Simple One-hot encoding and Hashing Technique are more similar, the only difference between them is the technique of tokenizing which also affects on result. 